IgaOAuthBundle:
    resource: "@IgaOAuthBundle/Controller/"
    type:     annotation
    prefix:   /

IgaSampleBundle:
    resource: "@IgaSampleBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
